---
- name: Create GCP Instance and PostgreSQL Database
  hosts: 34.136.192.212
  gather_facts: false
  tasks:
    - name: Install PostgreSQL
      become: yes
      apt:
        name: postgresql
        state: present

    - name: Create Database from SQL File
      become: yes
      community.general.postgresql_db:
        name: schedule
        login_host: "{{ DB_HOST }}"
        login_user: "{{ POSTGRES_USER }}"
        login_password: "{{ POSTGRES_PASSWORD }}"
        state: import
        target: "{{ PATH_TO_RESTORE_FILE }}"

    - name: Schedule SQL File to Run Every Minute
      become: yes
      cron:
        name: Run SQL File Every Minute
        minute: "*"
        job: "psql -h localhost -U {{ POSTGRES_USER }} -d schedule < {{ PATH_TO_FIX_SQL_FILE }}"

